// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmwpkhjskesblxdunrww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtd3BraGpza2VzYmx4ZHVucnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjU1NzYsImV4cCI6MjA2MDY0MTU3Nn0.paTZSHItHVdWC0FsHDSM3KfBULtWdmdzOEYE9qbtxWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);